# Generated by Django 4.1.13 on 2024-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeedID', models.CharField(max_length=100)),
                ('SeedType', models.CharField(max_length=255)),
                ('SeedQuantity', models.IntegerField()),
            ],
            options={
                'db_table': 'UserSeedCatalog',
            },
        ),
    ]
