# Generated by Django 4.1.13 on 2024-07-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0002_adminallusers_adminfeedback_adminseedcatalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentID', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=100)),
                ('LastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=100)),
                ('Reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreachID', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted', models.IntegerField(default=0)),
                ('in_inventory', models.IntegerField(default=0)),
                ('older', models.IntegerField(default=0)),
                ('newer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('AssignedPlace', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='worker_images/')),
            ],
        ),
    ]
